### PR TITLE
Menu provider

### PR DESCRIPTION
**Pull request by Id4v**

### CODE REVIEW

**Comment by Th3Mouk** [comment]
This PR completly break compatibily. All projects based on the 2.x branch are down.
It would be necessary to move this changes on a 3.x branch.

**Comment by Th3Mouk** [comment]
Why not using gulp to select only necessary assets ? There many useless files (accordion, search bar, many more)

**Comment by Id4v** [comment]
This changes are on the 3.x branch... Dev-Master : 3.x-dev
So yeah there are BC but it's normal as it's on a new major version branch.

Yeah for the moment, all the UiKit assets are inside the project. 
This will change as soon as I'm sure of what is used and what is not.

**Comment by Th3Mouk** [comment]
I've forgot to continu the 3.x process release, i've check they're no problem on 2.x, i'm tired i was thinking this PR was base on a master 2.x branch.
The provider / loader system seems really good, i probably have a look in few days

**Pull request merged**
